import numpy as np
from sdf import sphere, box, cylinder

def create_sample_shape():
    """
    테스트용 SDF 도형 정의
    예: 구(Sphere)에서 원기둥(Cylinder)을 뺀 형태
    """
    # 반지름 0.8인 구
    s = sphere(0.8)
    # Z축 방향의 원기둥 (구멍 뚫기용)
    c = cylinder(0.4)
    
    # 구 - 원기둥 (Boolean Difference)
    final_shape = s - c
    return final_shape

def to_grid(sdf_func, resolution=64, domain_size=2.0):
    """
    SDF 함수를 받아서 3D Numpy Grid로 변환
    
    Args:
        sdf_func: sdf 라이브러리로 만든 도형 함수
        resolution: 그리드 해상도 (기본 64)
        domain_size: 공간 크기 (예: 2.0이면 -1.0 ~ 1.0 범위)
    
    Returns:
        sdf_grid: (N, N, N) 모양의 Numpy 배열
    """
    # 좌표계 생성 (-1 ~ 1 사이를 resolution 등분)
    min_bound = -domain_size / 2
    max_bound = domain_size / 2
    
    x = np.linspace(min_bound, max_bound, resolution)
    y = np.linspace(min_bound, max_bound, resolution)
    z = np.linspace(min_bound, max_bound, resolution)
    
    # 3D 그리드 좌표 생성 (indexing='ij'는 행렬 순서인 z, y, x 순서에 맞춤)
    xx, yy, zz = np.meshgrid(x, y, z, indexing='ij')
    
    # (N, 3) 형태로 변환하여 SDF 계산
    points = np.stack([xx, yy, zz], axis=-1).reshape(-1, 3)
    
    # 계산 후 원래 모양 (N, N, N)으로 복원
    # sdf 라이브러리는 표면=0, 내부=음수, 외부=양수 리턴
    sdf_values = sdf_func(points).reshape(resolution, resolution, resolution)
    
    return sdf_values


def save_mesh_as_obj(sdf_grid, filename="output.obj", level=0):
    """
    Marching Cubes로 메쉬를 추출하여 OBJ 파일로 저장
    """
    try:
        # Marching Cubes 알고리즘 (SDF=0 인 등가면 추출)
        verts, faces, normals, values = measure.marching_cubes(sdf_grid, level=level)
        
        # OBJ 파일 쓰기
        with open(filename, 'w') as f:
            f.write(f"# OBJ file generated by Fluid Lab\n")
            # 정점(Vertex) 저장
            for v in verts:
                f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            # 면(Face) 저장 (OBJ는 인덱스가 1부터 시작하므로 +1)
            for face in faces:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
                
        print(f"✅ 메쉬 저장 완료: {filename} (Vertices: {len(verts)})")
        
    except Exception as e:
        print(f"❌ 메쉬 생성 실패: 데이터가 비어있거나 표면이 없습니다. ({e})")