import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from skimage import measure

def plot_slice(sdf_grid, axis=2, slice_idx=None):
    """
    3D 그리드의 단면을 잘라서 히트맵으로 보여줌 (내부 값 검증용)
    axis: 0(X축), 1(Y축), 2(Z축)
    """
    if slice_idx is None:
        slice_idx = sdf_grid.shape[axis] // 2  # 정중앙 자르기
    
    # 축에 따라 슬라이싱
    if axis == 0:
        data_slice = sdf_grid[slice_idx, :, :]
    elif axis == 1:
        data_slice = sdf_grid[:, slice_idx, :]
    else:
        data_slice = sdf_grid[:, :, slice_idx]
        
    plt.figure(figsize=(6, 5))
    plt.title(f"SDF Slice (Axis={axis}, Index={slice_idx})")
    # 빨강(+): 외부, 파랑(-): 내부, 흰색(0): 표면
    plt.imshow(data_slice, cmap='RdBu', vmin=-1, vmax=1, origin='lower')
    plt.colorbar(label='SDF Value')
    plt.contour(data_slice, levels=[0], colors='black', linewidths=2) # 표면 선 그리기
    plt.show()

def save_mesh_as_obj(sdf_grid, filename="output.obj", level=0):
    """
    Marching Cubes로 메쉬를 추출하여 OBJ 파일로 저장
    """
    try:
        # Marching Cubes 알고리즘 (SDF=0 인 등가면 추출)
        verts, faces, normals, values = measure.marching_cubes(sdf_grid, level=level)
        
        # OBJ 파일 쓰기
        with open(filename, 'w') as f:
            f.write(f"# OBJ file generated by Fluid Lab\n")
            # 정점(Vertex) 저장
            for v in verts:
                f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            # 면(Face) 저장 (OBJ는 인덱스가 1부터 시작하므로 +1)
            for face in faces:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
                
        print(f"✅ 메쉬 저장 완료: {filename} (Vertices: {len(verts)})")
        
    except Exception as e:
        print(f"❌ 메쉬 생성 실패: 데이터가 비어있거나 표면이 없습니다. ({e})")

def visualize_npy_sdf(filepath, vmin=-1, vmax=1):
    """
    .npy로 저장된 SDF 3D grid를 2D slice와 3D marching cubes로 시각화합니다.
    Args:
        filepath: npy 파일 경로
        vmin, vmax: 컬러맵 범위
    """

    try:
        grid_data = np.load(filepath)
        print(f"📂 파일 로드 성공! 데이터 크기: {grid_data.shape}")
    except FileNotFoundError:
        print("❌ 파일을 찾을 수 없습니다. 먼저 SDF를 저장하세요.")
        return

    # --- [시각화 1] 2D 단면 검사 ---
    mid_index = grid_data.shape[2] // 2
    slice_data = grid_data[:, :, mid_index]
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.title(f"2D Slice (Z={mid_index})")
    plt.imshow(slice_data, cmap='RdBu', vmin=vmin, vmax=vmax, origin='lower')
    plt.colorbar(label='SDF Value')
    plt.contour(slice_data, levels=[0], colors='black', linewidths=2)

    # --- [시각화 2] 3D 형상 복원 (마칭 큐브) ---
    verts, faces, normals, values = measure.marching_cubes(grid_data, level=0)
    ax = plt.subplot(1, 2, 2, projection='3d')
    mesh = Poly3DCollection(verts[faces], alpha=0.70)
    mesh.set_facecolor('skyblue')
    mesh.set_edgecolor('k')
    mesh.set_linewidth(0.1)
    ax.add_collection3d(mesh)
    ax.set_xlim(0, grid_data.shape[0])
    ax.set_ylim(0, grid_data.shape[1])
    ax.set_zlim(0, grid_data.shape[2])
    ax.set_title(f"3D Reconstruction ({len(verts)} vertices)")
    plt.tight_layout()
    plt.show()

def plot_particles_and_sdf_slice(sdf_grid, particles, axis=2, slice_idx=None):
    """
    SDF 단면(2D) 위에 파티클 위치를 함께 시각화합니다.
    Args:
        sdf_grid: (N,N,N) SDF 배열
        particles: (M,3) 파티클 좌표 (월드 좌표계)
        axis: 단면 축 (0,1,2)
        slice_idx: 단면 인덱스 (None이면 중앙)
    """
    import matplotlib.pyplot as plt
    import numpy as np
    N = sdf_grid.shape[axis]
    if slice_idx is None:
        slice_idx = N // 2
    # SDF 단면 추출
    if axis == 0:
        sdf_slice = sdf_grid[slice_idx, :, :]
        x, y = 1, 2
    elif axis == 1:
        sdf_slice = sdf_grid[:, slice_idx, :]
        x, y = 0, 2
    else:
        sdf_slice = sdf_grid[:, :, slice_idx]
        x, y = 0, 1
    plt.figure(figsize=(7,6))
    plt.title(f"SDF Slice + Particles (axis={axis}, idx={slice_idx})")
    plt.imshow(sdf_slice, cmap='RdBu', vmin=-1, vmax=1, origin='lower')
    plt.colorbar(label='SDF Value')
    plt.contour(sdf_slice, levels=[0], colors='black', linewidths=2)
    # 파티클을 그리드 인덱스로 변환
    domain_size = 2.0
    min_bound = -domain_size/2
    max_bound = domain_size/2
    res = sdf_grid.shape[0]
    voxel_size = domain_size / (res-1)
    # 월드좌표 -> 인덱스
    idx_x = np.clip(np.round((particles[:,x] - min_bound) / voxel_size), 0, res-1)
    idx_y = np.clip(np.round((particles[:,y] - min_bound) / voxel_size), 0, res-1)
    plt.scatter(idx_y, idx_x, s=5, c='yellow', edgecolors='k', alpha=0.7, label='Particles')
    plt.legend()
    plt.show()
    
def plot_particles_and_mesh(sdf_grid, particles, domain_size=2.0, level=0):
    """
    SDF로 추출한 3D 메쉬와 파티클을 같은 좌표계에서 시각화합니다.
    
    Args:
        sdf_grid: (N,N,N) SDF 배열 (값)
        particles: (M,3) 파티클 좌표 (월드 좌표계)
        domain_size: 물리적 공간 크기 (예: 2.0이면 -1.0 ~ 1.0)
        level: 마칭큐브 등가면 값 (보통 0)
    """
    
    # 1. Marching Cubes (그리드 인덱스 좌표 추출: 0 ~ N-1)
    try:
        verts, faces, normals, values = measure.marching_cubes(sdf_grid, level=level)
    except ValueError:
        print("⚠️ 경고: 등가면(Surface)을 찾을 수 없습니다. (SDF가 모두 양수거나 음수임)")
        return

    # 2. [중요] 메쉬 좌표 변환 (Index -> World)
    # 공식: MinBound + (Index / (Resolution-1)) * DomainSize
    resolution = sdf_grid.shape[0]
    min_bound = -domain_size / 2.0
    
    # 정점 좌표 스케일링
    verts_world = min_bound + verts * (domain_size / (resolution - 1))

    # 3. 시각화 설정
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')

    # (1) 메쉬 그리기 (투명하게)
    mesh = Poly3DCollection(verts_world[faces], alpha=0.15) # 투명도 높임
    mesh.set_facecolor('skyblue')
    mesh.set_edgecolor('gray')
    mesh.set_linewidth(0.1)
    ax.add_collection3d(mesh)

    # (2) 파티클 그리기 (최적화)
    # 파티클이 너무 많으면 뷰어가 느려지므로 최대 2000개만 샘플링해서 보여줌
    if len(particles) > 2000:
        step = len(particles) // 2000
        p_show = particles[::step]
    else:
        p_show = particles
        
    ax.scatter(p_show[:, 0], p_show[:, 1], p_show[:, 2], 
               s=3, c='orange', alpha=0.8, label='Particles')

    # 4. 축 범위 설정 (도형 전체가 보이도록 고정)
    limit = domain_size / 2.0
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.set_zlim(-limit, limit)

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(f'SDF Mesh + Particles ({len(particles)} count)')
    ax.legend(loc='upper right')
    
    plt.tight_layout()
    plt.show()