import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from mpl_toolkits.mplot3d import Axes3D
from skimage import measure
import torch

import open3d as o3d
import os

# =========================================================
# 0. 메쉬 저장 함수 (OBJ 파일로 저장) 
# =========================================================

def save_mesh_as_obj(sdf_grid, filename="output.obj", level=0):
    """
    Marching Cubes로 메쉬를 추출하여 OBJ 파일로 저장
    """
    try:
        # Marching Cubes 알고리즘 (SDF=0 인 등가면 추출)
        verts, faces, normals, values = measure.marching_cubes(sdf_grid, level=level)
        
        # OBJ 파일 쓰기
        with open(filename, 'w') as f:
            f.write(f"# OBJ file generated by Fluid Lab\n")
            # 정점(Vertex) 저장
            for v in verts:
                f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
            # 면(Face) 저장 (OBJ는 인덱스가 1부터 시작하므로 +1)
            for face in faces:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
                
        print(f"✅ 메쉬 저장 완료: {filename} (Vertices: {len(verts)})")
        
    except Exception as e:
        print(f"❌ 메쉬 생성 실패: 데이터가 비어있거나 표면이 없습니다. ({e})")

# =========================================================
# 1. 3D 시각화 관련 함수들 (이전과 동일)
# =========================================================

def draw_sdf_mesh(ax, sdf_grid, domain_size=2.0, level=0, color='skyblue', alpha=0.2):
    """3D 축에 SDF 메쉬를 그림"""
    try:
        verts, faces, normals, values = measure.marching_cubes(sdf_grid, level=level)
        resolution = sdf_grid.shape[0]
        min_bound = -domain_size / 2.0
        voxel_size = domain_size / (resolution - 1)
        verts_world = min_bound + verts * voxel_size
        
        mesh = Poly3DCollection(verts_world[faces], alpha=alpha)
        mesh.set_facecolor(color)
        mesh.set_edgecolor('gray')
        mesh.set_linewidth(0.05)
        ax.add_collection3d(mesh)
        return True
    except (ValueError, RuntimeError):
        return False

def draw_particles(ax, particles, color='orange', size=3, max_show=2000):
    """3D 축에 파티클을 그림"""
    if particles is None or len(particles) == 0: return
    
    p_show = particles[::(len(particles)//max_show)] if len(particles) > max_show else particles
    ax.scatter(p_show[:, 0], p_show[:, 1], p_show[:, 2], 
               s=size, c=color, alpha=0.8, label=f'Particles ({len(particles)})')

# =========================================================
# 2. 2D 단면 시각화 관련 함수들 (리팩토링 핵심)
# =========================================================

def draw_2d_slice(ax, sdf_grid, particles=None, axis=2, slice_idx=None, domain_size=2.0):
    """
    SDF 그리드의 단면을 자르고, 필요시 파티클을 투영하여 그립니다.
    """
    N = sdf_grid.shape[axis]
    if slice_idx is None:
        slice_idx = N // 2 # 중앙

    # 1. 단면 자르기 (Slicing)
    if axis == 0:   # X축 기준 자르기 (YZ 평면)
        data_slice = sdf_grid[slice_idx, :, :]
        idx_x_particle, idx_y_particle = 1, 2 # 파티클의 Y, Z 좌표 사용
        xlabel, ylabel = 'Y', 'Z'
    elif axis == 1: # Y축 기준 자르기 (XZ 평면)
        data_slice = sdf_grid[:, slice_idx, :]
        idx_x_particle, idx_y_particle = 0, 2 # 파티클의 X, Z 좌표 사용
        xlabel, ylabel = 'X', 'Z'
    else:           # Z축 기준 자르기 (XY 평면)
        data_slice = sdf_grid[:, :, slice_idx]
        idx_x_particle, idx_y_particle = 0, 1 # 파티클의 X, Y 좌표 사용
        xlabel, ylabel = 'X', 'Y'

    # 2. 히트맵 그리기
    im = ax.imshow(data_slice.T, # 축 방향에 따라 전치 필요할 수 있음 (여기선 보정)
                   cmap='RdBu', vmin=-1, vmax=1, origin='lower')
    ax.contour(data_slice.T, 
               levels=[0], colors='black', linewidths=2)
    
    # 3. 파티클 오버레이 (World -> Grid Index 변환 및 투영)
    if particles is not None and len(particles) > 0:
        resolution = sdf_grid.shape[0]
        voxel_size = domain_size / (resolution - 1)
        min_bound = -domain_size / 2.0

        # 파티클 좌표를 그리드 인덱스로 변환
        p_indices = (particles - min_bound) / voxel_size
        
        # 현재 슬라이스 두께(1칸) 안에 들어오는 파티클만 필터링
        # 예: Z축 슬라이스면, 파티클의 Z 인덱스가 slice_idx와 비슷한 것만 골라냄
        slice_axis_idx = axis
        mask = np.abs(p_indices[:, slice_axis_idx] - slice_idx) < 0.6 # ±0.6칸 이내
        
        valid_p = p_indices[mask]
        
        # 필터링된 파티클 그리기
        ax.scatter(valid_p[:, idx_x_particle], valid_p[:, idx_y_particle], 
                   s=10, c='yellow', edgecolors='k', alpha=0.8, label='Particles')
        ax.legend(loc='upper right', fontsize='small')

    ax.set_title(f"2D Slice ({ylabel} vs {xlabel}) @ idx={slice_idx}")
    ax.set_xlabel(f"{xlabel} Index")
    ax.set_ylabel(f"{ylabel} Index")
    return im

# =========================================================
# 3. 통합 실행 함수들 (사용자는 이것만 호출하면 됨)
# =========================================================

def visualize_simulation(sdf_grid=None, particles=None, domain_size=2.0, title="Simulation Result"):
    """
    [통합 뷰어] 왼쪽에는 2D 단면, 오른쪽에는 3D 메쉬+파티클을 보여줍니다.
    """
    fig = plt.figure(figsize=(14, 6))
    
    # --- 왼쪽: 2D Slice ---
    ax1 = fig.add_subplot(1, 2, 1)
    if sdf_grid is not None:
        im = draw_2d_slice(ax1, sdf_grid, particles, axis=2, domain_size=domain_size)
        plt.colorbar(im, ax=ax1, label='SDF Value')
    else:
        ax1.text(0.5, 0.5, "No SDF Data", ha='center')

    # --- 오른쪽: 3D Mesh + Particles ---
    ax2 = fig.add_subplot(1, 2, 2, projection='3d')
    if sdf_grid is not None:
        draw_sdf_mesh(ax2, sdf_grid, domain_size)
    if particles is not None:
        draw_particles(ax2, particles)
        
    # 3D 축 설정
    limit = domain_size / 2.0
    ax2.set_xlim(-limit, limit); ax2.set_ylim(-limit, limit); ax2.set_zlim(-limit, limit)
    ax2.set_title(f"{title} (3D View)")
    
    plt.tight_layout()
    plt.show()


def visualize_npy(filepath, domain_size=2.0):
    """
    .npy 파일을 로드하여 시각화합니다.
    """
    try:
        data = np.load(filepath)
        print(f"📂 '{filepath}' 로드 성공! Shape: {data.shape}")
        
        # 데이터 모양에 따라 처리 (그리드인지 파티클인지)
        if len(data.shape) == 3: # SDF 그리드 (N,N,N)
            visualize_simulation(sdf_grid=data, domain_size=domain_size, title="Loaded SDF Grid")
        elif len(data.shape) == 2 and data.shape[1] == 3: # 파티클 (M,3)
            visualize_simulation(particles=data, domain_size=domain_size, title="Loaded Particles")
        else:
            print("❌ 알 수 없는 데이터 형식입니다.")
            
    except FileNotFoundError:
        print(f"❌ 파일을 찾을 수 없습니다: {filepath}")


def view_obj_interactive(filename="output.obj"):
    """
    Open3D를 사용하여 OBJ 파일을 별도의 창에서 인터랙티브하게 봅니다.
    마우스로 회전(좌클릭), 이동(우클릭), 줌(휠)이 가능합니다.
    """
    if not os.path.exists(filename):
        print(f"❌ 파일을 찾을 수 없습니다: {filename}")
        return

    print(f"🖥️ 3D 뷰어 실행 중: {filename} ...")
    
    try:
        # 1. 메쉬 읽기
        mesh = o3d.io.read_triangle_mesh(filename)
        
        # 2. 렌더링 품질 향상을 위한 법선 벡터(Normal) 계산
        # (이게 없으면 모델이 평평해 보임)
        mesh.compute_vertex_normals()
        
        # 3. 좌표축 표시 (선택사항)
        coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0, 0, 0])
        
        # 4. 시각화 창 띄우기
        o3d.visualization.draw_geometries(
            [mesh, coord_frame], 
            window_name="SDF 3D Viewer",
            width=800,
            height=600,
            left=50,
            top=50
        )
        print("✅ 뷰어 종료됨.")
        
    except Exception as e:
        print(f"❌ 뷰어 실행 중 오류 발생: {e}")


# =========================================================
# 4. SDF Network 시각화 함수들
# =========================================================

def visualize_feature_grid(m_c_grid: torch.Tensor, 
                          grid_nodes: torch.Tensor,
                          title: str = "Grid Features (m_c)",
                          figsize: tuple = (10, 8)) -> plt.Figure:
    """
    그리드 특징값(m_c) 시각화
    
    Args:
        m_c_grid: (G,) 1D 배열 형태의 특징값
        grid_nodes: (G, 3) 그리드 노드 좌표
        title: 그래프 제목
        figsize: 그림 크기
    
    Returns:
        fig: matplotlib Figure 객체
    """
    fig = plt.figure(figsize=figsize)
    ax = fig.add_subplot(111, projection='3d')
    
    # 텐서를 numpy 배열로 변환
    m_c_flat = m_c_grid.cpu().numpy() if isinstance(m_c_grid, torch.Tensor) else m_c_grid
    m_c_flat = m_c_flat.flatten()
    
    grid_np = grid_nodes.cpu().numpy() if isinstance(grid_nodes, torch.Tensor) else grid_nodes
    
    # 길이 보정: 데이터 개수가 일치하지 않는 경우를 대비한 안전 로직 (파티클 기반의 동적 추출일 때)
    # min_len = min(len(m_c_flat), len(grid_np))
    # m_c_flat = m_c_flat[:min_len]
    # grid_np = grid_np[:min_len]

    mask = m_c_flat > 1e-5  # 값이 아주 작은 노이즈와 0을 걸러냅니다.
    
    m_c_filtered = m_c_flat[mask]
    grid_filtered = grid_np[mask]
    
    scatter = ax.scatter(
        grid_filtered[:, 0],
        grid_filtered[:, 1],
        grid_filtered[:, 2],
        c=m_c_filtered,
        cmap='viridis',
        s=10,
        alpha=0.4
    )
    
    cbar = plt.colorbar(scatter, ax=ax, label='m_c value')
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(title)
    plt.tight_layout()
    return fig


def visualize_sdf(sdf_values: torch.Tensor, 
                 grid_nodes: torch.Tensor,
                 title: str = "SDF Reconstruction",
                 figsize: tuple = (10, 8)) -> plt.Figure:
    """
    SDF 값 시각화
    
    Args:
        sdf_values: (G,) SDF 값
        grid_nodes: (G, 3) 그리드 노드 좌표
        title: 그래프 제목
        figsize: 그림 크기
    
    Returns:
        fig: matplotlib Figure 객체
    """
    fig = plt.figure(figsize=figsize)
    ax = fig.add_subplot(111, projection='3d')
    
    sdf_np = sdf_values.cpu().numpy() if isinstance(sdf_values, torch.Tensor) else sdf_values
    scatter = ax.scatter(
        grid_nodes[:, 0].cpu().numpy() if isinstance(grid_nodes, torch.Tensor) else grid_nodes[:, 0],
        grid_nodes[:, 1].cpu().numpy() if isinstance(grid_nodes, torch.Tensor) else grid_nodes[:, 1],
        grid_nodes[:, 2].cpu().numpy() if isinstance(grid_nodes, torch.Tensor) else grid_nodes[:, 2],
        c=sdf_np,
        cmap='RdBu',
        s=10,
        alpha=0.6
    )
    
    cbar = plt.colorbar(scatter, ax=ax, label='SDF value')
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(title)
    plt.tight_layout()
    
    plt.show()
    return fig


def visualize_particles_and_features(particles: torch.Tensor,
                                     grid_nodes: torch.Tensor,
                                     m_c_grid: torch.Tensor,
                                     title: str = "Particles and Grid Features",
                                     figsize: tuple = (12, 8)) -> plt.Figure:
    """
    파티클과 그리드 특징값 함께 시각화
    
    Args:
        particles: (N, 3) 파티클 좌표
        grid_nodes: (G, 3) 그리드 노드 좌표
        m_c_grid: (Gx, Gy, Gz) 또는 (G,) 그리드 특징값
        title: 그래프 제목
        figsize: 그림 크기
    
    Returns:
        fig: matplotlib Figure 객체
    """
    fig = plt.figure(figsize=figsize)
    ax = fig.add_subplot(111, projection='3d')
    
    # 파티클 시각화 (빨간색)
    particles_np = particles.cpu().numpy() if isinstance(particles, torch.Tensor) else particles
    ax.scatter(particles_np[:, 0],
               particles_np[:, 1],
               particles_np[:, 2],
               c='red', s=30, label='Particles', alpha=0.7)
    
    # 그리드 노드 시각화 (색상: m_c 값)
    if isinstance(m_c_grid, torch.Tensor):
        m_c_flat = m_c_grid.reshape(-1).cpu().numpy()
    else:
        m_c_flat = m_c_grid.reshape(-1) if m_c_grid.ndim > 1 else m_c_grid
    
    grid_nodes_np = grid_nodes.cpu().numpy() if isinstance(grid_nodes, torch.Tensor) else grid_nodes
    scatter = ax.scatter(
        grid_nodes_np[:, 0],
        grid_nodes_np[:, 1],
        grid_nodes_np[:, 2],
        c=m_c_flat,
        cmap='viridis',
        s=3,
        alpha=0.1,
        label='Grid nodes'
    )
    
    plt.colorbar(scatter, ax=ax, label='m_c value')
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(title)
    ax.legend()
    plt.tight_layout()
    plt.show()
    
    return fig